### ISSUE TITLE
Indexing blocks nesting

### ISSUE THREAD

**Issue by mlubin** [domluna/JuliaFormatter.jl#125]
```julia
julia> print(JuliaFormatter.format_text("long_name = sum(a_very_very_long_name[i])", margin=30))
long_name = sum(a_very_very_long_name[i])
julia> print(JuliaFormatter.format_text("long_name = sum(a_very_very_long_name)", margin=30))
long_name = sum(
    a_very_very_long_name,
)
```
The first case doesn't satisfy the margins. I expected it to be formatted as:
```julia
long_name = sum(
    a_very_very_long_name[i],
)
```

I do not know if this is related to #123 and #124.

**Comment by domluna** [comment]
@mlubin this wold now be formatted as

```julia
long_name =
    sum(a_very_very_long_name[i])
```
The reason this does not become 

```julia
long_name = sum(
    a_very_very_long_name[i],
)
```

enough though it's past the margin at the moment is due to the rule if the single argument of an iterable type (types with opening/closing punctuation, i.e. (), {}, []) is an iterable type won't insert PLACEHOLER nodes to possibly nest it.

This is due to a limitation with "dedenting". I think I have a solution that would make this work fine. But currently it's done this way to avoid

```julia
long_name = sum(
    a_very_very_long_name[
       i,
    ],
)
```

**Comment by domluna** [comment]
Didn't mean to close this 1. Not 100% sure it's resolved. 

Anyway I'm going to work on a more robust dedenting approach which should resolve this and produce nicer output in other edge cases as well.

**Comment by mlubin** [comment]
My motivating example is now fixed, but I see that other cases might not be. Thanks!

**Comment by domluna** [comment]
#132 fixes the issues I was referring to. I'll probably revisit the single argument `PLACEHOLDER` rule thing now.
