### ISSUE TITLE
Upgrade to CSTParser 3

### ISSUE THREAD

**Issue by domluna** [domluna/JuliaFormatter.jl#349]
Now that CSTParser v3 has been tagged we should upgrade to it. The API looks to have changed significantly so this will likely quite involved.

The main change will be updating the `FST` struct

```julia
mutable struct FST
    typ::Union{CSTParser.Head,FNode}

    # Start and end lines of the node
    # in the original source file.
    startline::Int
    endline::Int

    indent::Int
    len::Int
    val::Union{Nothing,AbstractString}
    nodes::Union{Nothing,Vector{FST}}
    ref::Union{Nothing,Ref{CSTParser.EXPR}}
    nest_behavior::NestBehavior

    # Extra margin caused by parent nodes.
    # i.e. `(f(arg))`
    #
    # `f(arg)` would have `extra_margin` = 1
    # due to `)` after `f(arg)`.
    extra_margin::Int
    line_offset::Int
end
```

Particularly the `typ` field - I think most of the other fields will fall into place. `CSTParser.Head` is no longer a thing afaict so we have to figure out the type of the expression somehow. The node structure of the CST may also have changed for some types, if so, we'll need to update those. We might be able to use the new trivia/meta fields to get rid of some helper code and the reference to the CST node but that's TBD.

@ZacLN @pfitzseb any guidance would be helpful

**Comment by ZacLN** [comment]
Hiya, I'd change `typ::Union{CSTParser.Head,FNode}` to `head::Union{Symbol,CSTParser.EXPR,FNode} for a start and work from there. `CSTParser.Head` are now represented by a `Symbol` as for AST, or where the head is an operator (e.g. `=`) the expression header is an `EXPR`.  Expression headers for literals (e.g. strings, numbers) are a capitalised version of the CSTParser.Head that they replace (e.g. CSTParser.StringH is now :STRING). 

Some other relevant info:
* Punctuation EXPR have headings like :COMMA, :LPAREN, etc.
* Nodes of an expression are now stored in two arrays `.args` and `.trivia` (the former holds sub-nodes that would be represented in the AST, the latter holds punctuation, etc). To iterate across them call `getindex` on the `EXPR` rather than  `EXPR.args` but this is slower.

You should be able to get pretty far in updating just by replacing all references to subtypes of `CSTParser.Head` with the correct symbol (this should hopefully be obvious, otherwise it's easily discoverable). Happy to look at a PR when things get tricky.

**Comment by ZacLN** [comment]
Also - have you considered storing all the info held by `FST` within the `EXPR.meta` node? That may save you redefining a whole bunch of methods

**Comment by domluna** [comment]
I'm not sure what that means

**Comment by ZacLN** [comment]
You have a type, `FST`, that looks like it basically extends `EXPR` to hold some extra info about each expression. You then have a bunch of methods (e.g. https://github.com/domluna/JuliaFormatter.jl/blob/master/src/fst.jl#L148:L149) that basically re-implement things that either are already in `CSTParser` or likely should be. If the structure for a FST tree matches that of the CST tree then you could simply store

**Comment by domluna** [comment]
@ZacLN is there a way to get the token kind of the operation (based on Tokenize.jl) ? I have some functionality where I check the use the old .kind field and match it with the Token. Or is there a new way to do this?

Also how does precedence work now, it seems CSTParser.precedence does not work the same it did before for ops

**Comment by ZacLN** [comment]
For the first i think `Tokenize.Tokens.UNICODE_OPS` is what you're looking for - it's a Dict that maps a `Char` of the operator to the token kind (you'll have to convert to Char and handle any suffixes).  [`CSTParser.get_prec`](https://github.com/julia-vscode/CSTParser.jl/blob/master/src/components/operators.jl#L467) takes the place of `precedence`.

**Comment by domluna** [comment]
this is g2g just waiting for a new CSTParser release (no rush)

**Comment by alok** [comment]
@domluna why the wait for a new release? does v3.1 of cstparser not work?

**Comment by domluna** [comment]
> @domluna why the wait for a new release? does v3.1 of cstparser not work?

yeah we need fixes currently on master

**Comment by ZacLN** [comment]
I think I fixed the relevant CSTParser issues yesterday - are there more?

**Comment by domluna** [comment]
Looks like everything works with this setup

```
     Testing Running tests...
Test Summary:  | Pass  Broken  Total
JuliaFormatter | 1055       2   1057
     Testing JuliaFormatter tests passed

(JuliaFormatter) pkg> st
     Project JuliaFormatter v0.14.0
      Status `~/.julia/dev/JuliaFormatter.jl/Project.toml`
  [00ebfdb7] CSTParser v3.1.1-DEV `https://github.com/julia-vscode/CSTParser.jl.git#master`
  [a80b9123] CommonMark v0.7.3
  [864edb3b] DataStructures v0.18.9
  [e30172f5] Documenter v0.26.3
  [0796e94c] Tokenize v0.5.16
  [44cfe95a] Pkg
```

**Comment by domluna** [comment]
@ZacLN @pfitzseb when are you guys planning on a new release?

**Comment by pfitzseb** [comment]
I'd be happy to tag a new release tonight. Any objections, @ZacLN?

**Comment by ZacLN** [comment]
Nope, let's do it

**Comment by pfitzseb** [comment]
Alright, 3.2.0 is out.
