### ISSUE TITLE
Removes my empty lines, even when setting the option to not remove any extra lines.

### ISSUE THREAD

**Issue by KwatME** [domluna/JuliaFormatter.jl#399]
![Screen Shot 2021-04-13 at 16 25 13](https://user-images.githubusercontent.com/7741548/114633316-28876280-9c75-11eb-87ac-7aab4190484d.png)
![Screen Shot 2021-04-13 at 16 27 31](https://user-images.githubusercontent.com/7741548/114633321-2ae9bc80-9c75-11eb-906f-6df8e6c65f08.png)

```sh
julia --eval "using JuliaFormatter; format(\".\")" 
```

![Screen Shot 2021-04-13 at 16 25 49](https://user-images.githubusercontent.com/7741548/114633325-2c1ae980-9c75-11eb-94de-9ac347aca552.png)

Please don't collapse any of my lines.

Thank you,
Kwat

**Comment by KwatME** [comment]
If you could give me a pointer, I can take on this issue and do a pull request too. Let me know @domluna .

**Comment by domluna** [comment]
I haven't taken a good look but I would start I would be removed because of this

https://github.com/domluna/JuliaFormatter.jl/blob/master/src/fst.jl#L382-L396

https://github.com/domluna/JuliaFormatter.jl/blob/master/src/fst.jl#L596-L602

So you have to check the output of CSTParser on that for loop. Sometimes it gives you nodes you wouldn't expect, this might be happening here.

**Comment by KwatME** [comment]
I think it's better you edit these core codes because I may break other parts you are more aware of.

I also notices that the extra line after a "for" statement is treated differently than after a "if" statement.

![Screen Shot 2021-04-16 at 11 37 41](https://user-images.githubusercontent.com/7741548/115069415-5ef8f380-9ea8-11eb-9a93-8a31f08f816c.png)
