### ISSUE TITLE
Positional argument changed to keyword argument in `Base.@deprecate` macro

### ISSUE THREAD

**Issue by devmotion** [domluna/JuliaFormatter.jl#494]
JuliaFormatter (blue style) wants to replace positional with keyword arguments in `Base.@deprecate`, i.e., it wants to change something like `Base.@deprecate f(x, y=x) g(x, y)` to `Base.@deprecate f(x; y=x) g(x, y)`. This showed up in a slightly lengthier example in https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/pull/388#discussion_r732840758.

**Comment by domluna** [comment]
by not a bug I meant that right now the formatter should make that transform so it's good it does that, but the bad  news is that  breaks things when the code is evaluated.

I guess disabling this transform for macros is the way to go, macros are tricky in this regard since they can break quite easily. trailing commas are not added to macro calls for this reason
