### ISSUE TITLE
Long, one-line functions with multiple statements require two passes

### ISSUE THREAD

**Issue by SBuercklin** [domluna/JuliaFormatter.jl#507]
This shows up with `BlueStyle()` but not the default `format`. I haven't narrowed down the precise settings to reproduce it.

If a one-line function definition is long enough that it exceeds the width to wrap, the function will expand to a long `function ... end` block with the contents reproduced exactly. However, a second `format` pass rewrites the contents of this function with another return statement.

This is a consequence of bad code style in the first place (the original function should probably use the long definition), so I'm not sure if this should be caught by `JuliaFormatter`. The problem is the outer `return` after the second pass.

Example:
```julia
julia> myfun = format_text("f(A_VERY_LOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOONG_NAME) = (1+1; return 2)", BlueStyle())
"function f(A_VERY_LOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOONG_NAME)\n    (1 + 1; return 2)\nend"

julia> myfun2 = format_text(myfun, BlueStyle())
"function f(A_VERY_LOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOONG_NAME)\n    return (1 + 1; return 2)\nend"

julia> @assert myfun == myfun2
ERROR: AssertionError: myfun == myfun2
Stacktrace:
 [1] top-level scope at REPL[33]:1```

**Comment by domluna** [comment]
this could be considered a bug in the heuristic that adds the return keyword. Since it doesn't see a return keyword already exists in the sub expression. Maybe checking if this expression has a return keyword already would be sufficient solution?

Alternatively, (i+1; return 2) could be rewritten as 

```
i+1
return 2
```

during the short to long transform, in which case the current heuristic would work fine.
