### ISSUE TITLE
Line endings on Windows files

### ISSUE THREAD

**Issue by PGS62** [domluna/JuliaFormatter.jl#98]
On Windows, line endings are given by CRLF (two characters, ascii 13 then ascii 10) whereas on Unix it's simply LF. When operating on Windows files, `format_file` produces a file with mixed line endings, some CRLF, some LF,  which I then need to correct (using Notepad++).

Could the function respect Windows line endings please?

**Comment by domluna** [comment]
Could you provide a minimal example? I don't have a Windows comp so it'll be tricky me to diagnose this.

**Comment by StefanKarpinski** [comment]
This is a bit of a subtle issue. Certainly it should recognize `\r\n` as a line ending, but I suspect it already does (since Julia does, by default). Should formatting a file one system produce a different file than on another system? Should running the formatter on Windows use `\r\n` for all lines? That means of two people work on a file, one on Linux, one on Windows, the entire file will keep switching back and forth between line ending styles. Otherwise, this may result in files with mixed line endings, which is also bad. I think that normalizing line endings to one style (and `\n`) is the standard is the reasonable thing to do.

**Comment by domluna** [comment]
I suspect why some lines endings are different is due to comments,
docstrings, and now unformatted code being copied directly. So if those end
in the windows line ending they will remain the same.

**Comment by StefanKarpinski** [comment]
Right, seems like they should all get normalized to `\n`.

**Comment by PGS62** [comment]
Stefan was correct to say that what I'm "against" is mixed line endings (it exposed a fragility in some not-Julia code of mine). Normalising to `\n` would be a great way to go.

**Comment by PGS62** [comment]
[adhoc4.zip](https://github.com/domluna/JuliaFormatter.jl/files/3773087/adhoc4.zip)

In case @domluna still needs an example file, I have attached one. Its line endings are currently `\r\n` but after running JuliaFormatter most (but not all) of the line endings become `\n`

**Comment by domluna** [comment]
@PGS62 is it the comment that does not become `\n`?

Which line endings don't become `\n`?

**Comment by PGS62** [comment]
@domluna I've attached "before" and "after" versions of the file, generated on my Windows PC. The "before" file has `\r\n` as a line ending on all lines.  The "after" file has `\r\n` as line ending on the first line (which is a comment), but `\n` on all remaining lines, including the two "empty" lines at the end of the file. That sounds like what you expected would be the case.
[Before and After.zip](https://github.com/domluna/JuliaFormatter.jl/files/3773444/Before.and.After.zip)

**Comment by StefanKarpinski** [comment]
A quick hack way to do this would be to normalize to `\n` before or after doing anything else 😬

**Comment by StefanKarpinski** [comment]
Tangentially related, it would be great if JuliaFormatter always produced files ending with `\n`.

**Comment by davidanthoff** [comment]
We're starting to look through the codebase here with an eye to move the LanguageServer.jl formatting over to JuliaFormatter.jl, and this is one issue here that is probably blocking from our end: we can't have the formatter always produce files with `\n` as line ending because that really doesn't work well with a default git installation on Windows. A default git installation on Windows has `autocrlf=true`, and so you end up in an eternal loop of JuliaFormatter.jl changing line endings to `\n`, and then git changing them back to `\r\n`.

I _do_ think it makes sense to normalize line endings in files, but I think the ideal implementation would do the same thing that VS Code does: at read, count whether `\r\n` or `\n` is used more often in the file, and then use the more common line-ending pattern throughout the file.

@domluna could you maybe reopen this issue? And maybe it would make sense to create a new label for things that we need to sort out before we can use this in LanguageServer?

CC @pfitzseb and @ZacLN

**Comment by domluna** [comment]
@davidanthoff sure

I don't have a Windows installation so it would be difficult for me to test this but it shouldn't be hard to make this adjustment.

perhaps make another arg here that's Pair{String,String}
https://github.com/domluna/JuliaFormatter.jl/blob/master/src/JuliaFormatter.jl#L83

do some sort of count here and then pass the correct normalize pairing
https://github.com/domluna/JuliaFormatter.jl/blob/master/src/JuliaFormatter.jl#L361
